httpcompression is now get-content-encoding
@alrra maintains it now. See alrra/dotfiles#18.

Hopefully it can be moved to its own repository and installed through npm/brew soon.

diff --git a/bin/get-content-encoding b/bin/get-content-encoding
--- a/bin/get-content-encoding
+++ b/bin/get-content-encoding
@@ -1,13 +1,13 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 # DESCRIPTION:
 #
-#   Provides the content encoding the specified
-#   resources are served with.
+#   Provides the content encoding the
+#   specified resources are served with.
 #
 # USAGE:
 #
-#   httpcompression URL ...
+#   get-content-encoding URL ...
 #
 # USEFUL LINKS:
 #
@@ -21,7 +21,7 @@
 
 declare -r -a CURL_DEFAULT_OPTIONS=(
     --connect-timeout 30
-    --header "Accept-Encoding: br, lzma, gzip, deflate, sdch"
+    --header "Accept-Encoding: br, gzip, deflate, lzma, sdch"
     --header "Cache-Control: no-cache" # Prevent intermediate proxies
                                        # from caching the response
 
@@ -40,12 +40,12 @@ declare -r -a CURL_DEFAULT_OPTIONS=(
 
 check_for_sdch() {
 
-    declare availDicts=""
+    declare availDicts=''
     declare currentHeaders="$1"
-    declare dict=""
-    declare dictClientID=""
-    declare dicts=""
-    declare i=""
+    declare dict=''
+    declare dictClientID=''
+    declare dicts=''
+    declare i=''
     declare url="$2"
 
     # Check if the server advertised any dictionaries
@@ -58,7 +58,7 @@ check_for_sdch() {
     if [ -n "$dicts" ]; then
         for i in $dicts; do
 
-            dict=""
+            dict=''
 
             # Check if the dictionary location is specified as a path,
             # and if it is, construct it's URL from the host name of the
@@ -105,11 +105,11 @@ check_for_sdch() {
 
 get_content_encoding() {
 
-    declare currentHeaders=""
-    declare encoding=""
-    declare headers=""
-    declare indent=""
-    declare tmp=""
+    declare currentHeaders=''
+    declare encoding=''
+    declare headers=''
+    declare indent=''
+    declare tmp=''
     declare url="$1"
 
     headers="$(curl "${CURL_DEFAULT_OPTIONS[@]}" \
@@ -167,17 +167,24 @@ get_content_encoding() {
 
 main() {
 
-    # Check if cURL is installed
-    if [ -x "$(command -v "curl")" ]; then
-        while [ $# -ne 0 ]; do
-            get_content_encoding "$1"
-            shift
-        done
-        printf "\n"
-    else
-        printf "cURL is required, please install it!\n"
+    # Check if `cURL` is installed
+
+    command -v 'curl' &> /dev/null
+
+    if [ $? -ne 0 ]; then
+        printf 'cURL is required, please install it!\n'
+        exit 1
     fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    while [ $# -ne 0 ]; do
+        get_content_encoding "$1"
+        shift
+    done
+
+    printf '\n'
 
 }
 
-main $@
+main "$@"
